server:
    port: 7000
    banner:
      location: classpath.banner.txt


spring:
    devtools:
        remote:
           restart:
               enabled: true 
    datasource:
        url: jdbc:h2:mem:commerce;MODE=DB2
        username: sa
        password: sa
        driverClassName: org.h2.Driver
        
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: false
                jdbc:
                    time_zone: UTC
    h2:
        console.enabled: true
    sql:
        init:
             mode: always
             data-locations: classpath:/sql/custom-data-1.sql